### ISSUE TITLE
Lo tenes funcando?

### ISSUE THREAD

**Issue by lbonini** [fernandojmartin/facturador_afip#1]
Hola Como va?
Sabes que tenia pensado hacer una prueba de concepto para esto en puppeteer y veo que vos armaste este proyecto.
Lo tenes andando?
Soy newbie en Node pero te puedo ayudar.

**Comment by fernando2amigos** [comment]
Hola, cómo estás?

Sí, está funcionando. 
Está verde, y lo voy mejorando en los ratos libres.

También es mi proyecto mascota para empezar a trabajar con Node.
De momento maneja comprobantes C y E.
De esos comprobantes sólo genera Servicios.
Hay que ir expandiéndolo.

Luego pusheo el código.

**Comment by fernandojmartin** [comment]
Hola, cómo estás?

Sí, está funcionando.
Está verde, y lo voy mejorando en los ratos libres (que escasean bastante).

También es mi proyecto mascota para empezar a trabajar con Node.
De momento maneja comprobantes C y E.
De esos comprobantes sólo genera Servicios.
Hay que ir expandiéndolo.

Luego pusheo el código.

**Comment by lbonini** [comment]
Dale cuando puedas pushealo.
Se me ocurria armar un cliente en whatsapp que te deje facturar directo
desde ahí.

**Comment by fernandojmartin** [comment]
Subido!

Epa, está buena la idea.
Suena interesante poder llevarlo a cabo! Veamos cómo.

Fernando J. Martin

**Comment by lbonini** [comment]
CLOSED.

**Comment by lbonini** [comment]
Uyyy recién me acordé que me quedó este tema colgado. Estaba con otros proyectos y ni lo pude mirar. sorry
